import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'notecardproject.settings')

import django
django.setup()

import random
from notecards.models import Deck, Card
from django.contrib.auth.models import User

from django.utils.crypto import get_random_string


def addDeck(author, title, description):
    deck = Deck.objects.get_or_create(author=author,
                                      title=title,
                                      description=description)[0]
    deck.tags.add("autogenerated")
    deck.save()
    return deck


def addCard(deck, front, back):
    card = Card.objects.get_or_create(front=front,
                                      back=back,
                                      deck=deck)[0]
    card.save()
    return card


def randUser():
    users = User.objects.all()
    numUsers = len(users)
    return users[random.randint(0, numUsers - 1)]


def populate():
    print("Populating database...")
    for i in range(0, 200):
        deck = addDeck(randUser(),
                       get_random_string(length=random.randint(10, 20)),
                       get_random_string(length=random.randint(50, 500)))
        for i in range(0, random.randint(0, 20)):
            addCard(deck,
                    get_random_string(length=random.randint(5, 15)),
                    get_random_string(length=random.randint(5, 15)))
    print("Finished!")


if __name__ == '__main__':
    populate()
